[site]
title = "Portfolio of Joshua G. Albert"
base_url = "https://joshuaalbert.github.io"

[giscus]
repo = "joshuaalbert/joshuaalbert.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnkzMTUzMjMxNjQ="
category = "Announcements"
category_id = "DIC_kwDOEstzHM4C9UAr"
theme = "noborder_light"
