[site]
title = "Portfolio of Joshua G. Albert"
base_url = "https://joshuaalbert.github.io"

[giscus]
repo = "Joshuaalbert/joshuaalbert.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnkzMTUzMjMxNjQ="
category = "Comments"
category_id = ""
theme = "noborder_light"

