date_taken = "2015-07-30"
name = "Borderline"
description = "This photo was an accidental success. It was captured one balmy night in Cascais, Portugal. In a split second my model became camera shy, and it wound up being one of my favorite photos."
location = "Cascais"
camera = "Canon EOS 60D"
focal_length = "21mm"
aperture = "ƒ/3.5"
shutter_speed = "1/60s"
iso = "ISO 400"
