date_taken = "2015-07-11"
name = "Center of the web"
description = "Spider's are born knowing how to build these fantastic structures intuitively. Not only that, but they are given flexible material stronger than diamonds to do it with. They are both architect and builder. I love this photo in particular because of the central focal point, and both far- and near-field defocusing due to the angle of the picture."
location = "Birch Island, Canada"
camera = "Nikon D40"
lens = "Nikon AF-S DX Zoom-Nikkor 18-55mm f/3.5-5.6G ED II"
focal_length = "55mm"
aperture = "ƒ/5.6"
shutter_speed = "1/125s"
iso = "ISO 400"
