date_taken = "2015-03-08"
name = "Duckplomacy"
description = "An offering of friendship."
location = "Leiden, Netherlands"
camera = "Nikon D40"
lens = "Nikon AF-S DX Zoom-Nikkor 18-55mm f/3.5-5.6G ED II"
focal_length = "18mm"
aperture = "ƒ/9"
shutter_speed = "1/320s"
iso = "ISO 200"
