date_taken = "2015-07-25"
name = "Earl Le Gris"
description = "My family's cat, originally named Earl le Gris, is a rather large grey cat. I choose black and white -- because he is grey -- to make him the only true part of the photograph, while the rest of the photo appears to washout."
location = "Birch Island, Canada"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "113mm"
aperture = "ƒ/5.6"
shutter_speed = "1/160s"
iso = "ISO 2000"
