date_taken = "2015-07-25"
name = "Gaze of My Father"
description = "There is a striking aspect to taking a picture of someone who knows you well. There are years of history in their eyes. This is my father taken during the last summer of my master studies. I traveled back from university to spend the summer with him at our cottage."
location = "Northeastern Manitoulin and Islands, Canada"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "45mm"
aperture = "ƒ/5"
shutter_speed = "1/60s"
iso = "ISO 640"
