date_taken = "2015-07-28"
name = "Harbor by Moonlight"
description = "This panoramic photograph was taken in Cascais from a vantage point over the harbor. Due to the high dynamic range of light sources, the exposure had to be carefully adjusted for each frame of the panorama."
location = "Cascais, Portugal"
