date_taken = "2015-07-04"
name = "Lines of Paris from Montmartre"
description = "This photo was taken from the viewpoint of the Sacré-Cœur, Paris. The post-processing technique is one I've been working on, and involves breaking down the binary representation of the various colour channels."
location = "Paris, France"
