date_taken = "2015-04-06"
name = "Magic is happiness"
description = "This photo was one of my earliest attempts at light art. The delight of both fire, and magic are clear upon the model's face. The setting was a relaxed lounge which allowed experimenting with various sources of illumination."
location = "Leiden, The Netherlands"
camera = "Nikon D40"
lens = "Nikon AF-S DX Zoom-Nikkor 18-55mm f/3.5-5.6G ED II"
focal_length = "18mm"
aperture = "ƒ/4"
shutter_speed = "13s"
iso = "ISO 1600"
