date_taken = "2016-08-18"
name = "Photo 3"
description = ""
location = "Birch Island"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "100mm"
aperture = "ƒ/5.6"
shutter_speed = "1/160s"
iso = "ISO 400"
