date_taken = "2015-07-25"
name = "Sunset from Boat"
description = "This panoramic photo is taken with my father, and a young boy we took fishing. It is a typical sunset in McGregor Bay in Northern Ontario, Canada. The beauty of the place speaks for itself in this untouched photograph. This is known as rainbow country to some."
location = "Mcgregor Bay"
