date_taken = "2015-07-25"
name = "Camera Shy"
description = "This photo was taken at my family's cottage this summer. The model is my grandmother, who was camera shy. I really like this photo, as it gives a feeling of her character. The black and white aspect washes out the background, and brings out the pearls."
location = "Birch Island"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "47mm"
aperture = "ƒ/5"
shutter_speed = "1/60s"
iso = "ISO 400"
