date_taken = "2015-07-28"
name = "Coastline"
description = "The ocean fades to sky in this photo, making it almost appear as though the rocks are drifting away. A light day fog enhanced the feeling of surrealism on this extremely hot day."
location = "Cascais, Portugal"
