date_taken = "2015-07-26"
name = "Fireplace"
description = "I love watching log fires dance. I always see things in the flickering shadows. In black and white it's almost hard to tell that this is a fire. Some people see faces, what do you see?"
location = "Birch Island, Canada"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "87mm"
aperture = "ƒ/5.6"
shutter_speed = "1/60s"
iso = "ISO 1250"
