date_taken = "2015-07-29"
name = "Fortune Teller's Gaze"
description = "This was taken in a park in Lisbon, and is of a woman who was telling people their futures. In this photograph I simply wanted to capture a unique face, with a lot of character and a good smile. She was watching young people playing in the park when I took this one."
location = "Rua Nogueira e Sousa 8, Portugal"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "75mm"
aperture = "ƒ/5.6"
shutter_speed = "1/125s"
iso = "ISO 320"
