date_taken = "2015-07-26"
name = "Leaf"
description = "In this shot beauty emerges quite naturally, as she doesn't know I'm taking the photograph. The grainy appearance is due to the low light levels. Despite the fact that this looks like a vintage photo, the cell phone gives it away as modern."
location = "Birch Island, Canada"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "26mm"
aperture = "ƒ/4"
shutter_speed = "1/60s"
iso = "ISO 3200"
