date_taken = "2015-08-19"
name = "Mediteranian Boats"
description = "This shot was taken not far from Marseille, on a lovely daytrip to les Calanques. We did not make it to our destination for danger of forest fire, but luckily found this remote, beautiful, fishing village to lay in the sun by."
location = "Marseille, France"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "42mm"
aperture = "ƒ/8"
shutter_speed = "1/200s"
iso = "ISO 100"
