date_taken = "2016-08-27"
name = "Photo 8"
description = "Future love of my life in light art."
location = "Birch Island"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "53mm"
aperture = "ƒ/5.6"
shutter_speed = "30s"
iso = "ISO 200"
