date_taken = "2016-08-17"
name = "Photo 2"
description = "Hello there."
location = "Birch Island"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "135mm"
aperture = "ƒ/5.6"
shutter_speed = "1/80s"
iso = "ISO 320"
