date_taken = "2016-09-03"
name = "Photo 1"
description = ""
location = "Little Current, ON Canada"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "135mm"
aperture = "ƒ/5.6"
shutter_speed = "1/100s"
iso = "ISO 200"
