date_taken = "2015-07-04"
name = "Sacré-Cœur"
description = "This photo is from the side of the Sacré-Cœur in Paris, an uncommon angle of this famous building. The wide angle style highlights the curves, and black and white contrasts the grey sky against the myriad of detail in the Sacré-Cœur better."
location = "23 Rue de Pontoise, France"
