date_taken = "2015-03-30"
name = "Shiva Shanty"
description = "I arranged this shot so that it pleased me. I find the shadows lead the eye from the candle to the cannabis. Bebop is the name of a local coffee shop in Leiden. Shiva Shanty is the name of the cannabis."
location = "Leiden, Netherlands"
camera = "Nikon D40"
lens = "Nikon AF-S DX Zoom-Nikkor 18-55mm f/3.5-5.6G ED II"
focal_length = "55mm"
aperture = "ƒ/16"
shutter_speed = "6s"
iso = "ISO 200"
