date_taken = "2015-07-30"
name = "Surreal ship"
description = "When I saw this ship off in the distance, it seemed to be floating on a cloud. I took it as a sign to pull out my camera and capture it. I put the horizon and ship in the center so that the viewer know they are looking from far away."
location = "Cascais, Portugal"
camera = "Canon EOS 60D"
lens = "Canon EF-S 18-135mm f/3.5-5.6 IS"
focal_length = "135mm"
aperture = "ƒ/9"
shutter_speed = "1/500s"
iso = "ISO 100"
